{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "59157451-e67f-4379-8197-4095c0511875",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "from datetime import date, datetime, timedelta\n",
    "import calendar\n",
    "from pathlib import Path\n",
    "\n",
    "st.set_page_config(page_title=\"Weekly Planning Dashboard\", layout=\"wide\")\n",
    "\n",
    "# =========================\n",
    "# Theme\n",
    "# =========================\n",
    "PINK_BG = \"#F8E9ED\"\n",
    "PINK_HEADER = \"#E4C2CB\"\n",
    "PINK_DEEP = \"#D89CAC\"\n",
    "CREAM = \"#F7F1DF\"\n",
    "BLUE = \"#DCE6F4\"\n",
    "LAVENDER = \"#EEE7F7\"\n",
    "TEXT = \"#4F4447\"\n",
    "LINE = \"#E8D8DD\"\n",
    "GREEN = \"#DDEED8\"\n",
    "YELLOW = \"#F9E8B4\"\n",
    "ROSE = \"#F9D9DF\"\n",
    "WHITE = \"#FFFFFF\"\n",
    "SOFT_BG = \"#FCFAF9\"\n",
    "\n",
    "STATUS_BG = {\n",
    "    \"已完成\": GREEN,\n",
    "    \"進行中\": YELLOW,\n",
    "    \"未完成\": ROSE,\n",
    "}\n",
    "STATUS_TEXT = {\n",
    "    \"已完成\": \"#5A8156\",\n",
    "    \"進行中\": \"#9B7417\",\n",
    "    \"未完成\": \"#B56E7B\",\n",
    "}\n",
    "CATEGORY_BAR = {\n",
    "    \"學習成長\": \"#B8A2F5\",\n",
    "    \"日常生活\": \"#9EBCE5\",\n",
    "    \"自我照顧\": \"#A8D7B5\",\n",
    "}\n",
    "WEEKDAY_ORDER = [\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\"]\n",
    "\n",
    "# =========================\n",
    "# CSS\n",
    "# =========================\n",
    "st.markdown(\n",
    "    f\"\"\"\n",
    "    <style>\n",
    "    .stApp {{\n",
    "        background: {SOFT_BG};\n",
    "        color: {TEXT};\n",
    "    }}\n",
    "    .main .block-container {{\n",
    "        max-width: 1450px;\n",
    "        padding-top: 1rem;\n",
    "        padding-bottom: 2rem;\n",
    "    }}\n",
    "    .top-wrap {{\n",
    "        background: {PINK_HEADER};\n",
    "        border-radius: 18px;\n",
    "        padding: 18px 22px;\n",
    "        margin-bottom: 18px;\n",
    "        display: flex;\n",
    "        justify-content: space-between;\n",
    "        align-items: center;\n",
    "    }}\n",
    "    .top-title {{\n",
    "        font-size: 1.9rem;\n",
    "        font-weight: 700;\n",
    "        color: #3E3437;\n",
    "        margin-bottom: 4px;\n",
    "    }}\n",
    "    .top-sub {{\n",
    "        color: #6D6265;\n",
    "        font-size: 0.95rem;\n",
    "    }}\n",
    "    .shell-card {{\n",
    "        background: {WHITE};\n",
    "        border: 1px solid {LINE};\n",
    "        border-radius: 18px;\n",
    "        overflow: hidden;\n",
    "        box-shadow: 0 1px 2px rgba(0,0,0,0.02);\n",
    "    }}\n",
    "    .card-title {{\n",
    "        padding: 12px 16px;\n",
    "        font-size: 1.03rem;\n",
    "        font-weight: 700;\n",
    "        border-bottom: 1px solid {LINE};\n",
    "        color: #453A3D;\n",
    "    }}\n",
    "    .card-body {{\n",
    "        padding: 14px 16px 16px 16px;\n",
    "    }}\n",
    "    .calendar-title {{ background: {CREAM}; }}\n",
    "    .today-title {{ background: {BLUE}; }}\n",
    "    .summary-title {{ background: {LAVENDER}; }}\n",
    "    .calendar-grid {{\n",
    "        display: grid;\n",
    "        grid-template-columns: repeat(7, 1fr);\n",
    "        gap: 6px;\n",
    "        text-align: center;\n",
    "        align-items: center;\n",
    "    }}\n",
    "    .weekday-label {{\n",
    "        font-weight: 700;\n",
    "        color: #5A4F52;\n",
    "        padding: 4px 0 6px 0;\n",
    "    }}\n",
    "    .day-num {{\n",
    "        width: 32px;\n",
    "        height: 32px;\n",
    "        margin: 0 auto;\n",
    "        border-radius: 999px;\n",
    "        display: flex;\n",
    "        justify-content: center;\n",
    "        align-items: center;\n",
    "        color: #554C4F;\n",
    "        font-size: 0.94rem;\n",
    "    }}\n",
    "    .day-other {{ color: #BBB4B7; }}\n",
    "    .day-today {{\n",
    "        background: {PINK_DEEP};\n",
    "        color: white;\n",
    "        font-weight: 700;\n",
    "    }}\n",
    "    .small-note {{\n",
    "        color: #796E71;\n",
    "        font-size: 0.9rem;\n",
    "        line-height: 1.6;\n",
    "    }}\n",
    "    .mini-row {{\n",
    "        display: flex;\n",
    "        align-items: center;\n",
    "        justify-content: space-between;\n",
    "        gap: 12px;\n",
    "        padding: 7px 0;\n",
    "        border-bottom: 1px dashed #EFE5E8;\n",
    "        font-size: 0.95rem;\n",
    "    }}\n",
    "    .mini-row:last-child {{ border-bottom: none; }}\n",
    "    .badge {{\n",
    "        display: inline-block;\n",
    "        border-radius: 999px;\n",
    "        padding: 4px 10px;\n",
    "        font-size: 0.83rem;\n",
    "        font-weight: 700;\n",
    "        white-space: nowrap;\n",
    "    }}\n",
    "    .stats-grid {{\n",
    "        display: grid;\n",
    "        grid-template-columns: repeat(4, 1fr);\n",
    "        gap: 10px;\n",
    "        margin-bottom: 14px;\n",
    "    }}\n",
    "    .stats-box {{\n",
    "        background: white;\n",
    "        border: 1px solid {LINE};\n",
    "        border-radius: 14px;\n",
    "        text-align: center;\n",
    "        padding: 10px 8px;\n",
    "    }}\n",
    "    .stats-label {{\n",
    "        color: #786D71;\n",
    "        font-size: 0.84rem;\n",
    "    }}\n",
    "    .stats-num {{\n",
    "        margin-top: 4px;\n",
    "        font-size: 1.5rem;\n",
    "        font-weight: 800;\n",
    "        color: #453A3D;\n",
    "    }}\n",
    "    .progress-row {{\n",
    "        display: grid;\n",
    "        grid-template-columns: 78px 1fr 46px;\n",
    "        gap: 10px;\n",
    "        align-items: center;\n",
    "        margin: 8px 0;\n",
    "        font-size: 0.9rem;\n",
    "    }}\n",
    "    .bar-bg {{\n",
    "        height: 10px;\n",
    "        background: #F1EDF0;\n",
    "        border-radius: 999px;\n",
    "        overflow: hidden;\n",
    "    }}\n",
    "    .bar-fill {{\n",
    "        height: 100%;\n",
    "        border-radius: 999px;\n",
    "    }}\n",
    "    .control-strip {{\n",
    "        background: {PINK_BG};\n",
    "        border: 1px solid {LINE};\n",
    "        border-radius: 16px;\n",
    "        padding: 14px 16px;\n",
    "        margin-bottom: 14px;\n",
    "    }}\n",
    "    .day-card {{\n",
    "        background: white;\n",
    "        border: 1px solid {LINE};\n",
    "        border-radius: 18px;\n",
    "        overflow: hidden;\n",
    "        height: 100%;\n",
    "    }}\n",
    "    .day-header {{\n",
    "        background: {PINK_BG};\n",
    "        padding: 11px 15px;\n",
    "        border-bottom: 1px solid {LINE};\n",
    "        display: flex;\n",
    "        justify-content: space-between;\n",
    "        align-items: center;\n",
    "    }}\n",
    "    .day-header-title {{\n",
    "        font-size: 1.7rem;\n",
    "        font-weight: 700;\n",
    "        color: #403638;\n",
    "    }}\n",
    "    .day-header-date {{\n",
    "        font-size: 0.92rem;\n",
    "        color: #6E6467;\n",
    "        font-weight: 700;\n",
    "    }}\n",
    "    .day-head-row {{\n",
    "        display: grid;\n",
    "        grid-template-columns: 1fr 94px;\n",
    "        gap: 12px;\n",
    "        padding: 11px 15px 8px 15px;\n",
    "        font-size: 0.92rem;\n",
    "        font-weight: 700;\n",
    "        color: #5E5658;\n",
    "    }}\n",
    "    .day-list {{\n",
    "        padding: 0 15px 16px 15px;\n",
    "        min-height: 260px;\n",
    "    }}\n",
    "    .task-row {{\n",
    "        display: grid;\n",
    "        grid-template-columns: 1fr 94px;\n",
    "        gap: 12px;\n",
    "        align-items: center;\n",
    "        padding: 8px 0;\n",
    "        border-bottom: 1px dashed #F0E6E9;\n",
    "        font-size: 0.95rem;\n",
    "    }}\n",
    "    .task-row:last-child {{ border-bottom: none; }}\n",
    "    .task-name {{\n",
    "        display: flex;\n",
    "        align-items: center;\n",
    "        gap: 8px;\n",
    "    }}\n",
    "    .checkbox {{\n",
    "        width: 14px;\n",
    "        height: 14px;\n",
    "        border-radius: 4px;\n",
    "        border: 1.4px solid #CFC5C8;\n",
    "        flex: 0 0 auto;\n",
    "    }}\n",
    "    .memo-box {{\n",
    "        background: #FFFDF8;\n",
    "        border: 1px dashed #E5C8B8;\n",
    "        border-radius: 18px;\n",
    "        padding: 16px 18px 20px 18px;\n",
    "        min-height: 260px;\n",
    "    }}\n",
    "    .memo-title {{\n",
    "        font-size: 1.35rem;\n",
    "        font-weight: 700;\n",
    "        color: #9A7270;\n",
    "        margin-bottom: 14px;\n",
    "    }}\n",
    "    .footer-strip {{\n",
    "        margin-top: 18px;\n",
    "        background: {LAVENDER};\n",
    "        border-radius: 16px;\n",
    "        padding: 12px 18px;\n",
    "        color: #5F5659;\n",
    "        display: flex;\n",
    "        justify-content: space-between;\n",
    "        align-items: center;\n",
    "        font-size: 0.92rem;\n",
    "    }}\n",
    "    div[data-testid=\"stSelectbox\"] > div {{\n",
    "        border-radius: 12px;\n",
    "    }}\n",
    "    </style>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True,\n",
    ")\n",
    "\n",
    "# =========================\n",
    "# Data helpers\n",
    "# =========================\n",
    "DEFAULT_CSV = \"tasks.csv\"\n",
    "\n",
    "\n",
    "def create_sample_csv(path: str):\n",
    "    sample = pd.DataFrame(\n",
    "        [\n",
    "            [1, \"日文 L35\", \"學習成長\", \"未完成\", \"2026-04-21\", \"W17\", \"Mon\", \"\"],\n",
    "            [2, \"神經解剖複習\", \"學習成長\", \"進行中\", \"2026-04-21\", \"W17\", \"Mon\", \"\"],\n",
    "            [3, \"英單 30 個\", \"學習成長\", \"已完成\", \"2026-04-21\", \"W17\", \"Mon\", \"\"],\n",
    "            [4, \"洗衣服\", \"日常生活\", \"已完成\", \"2026-04-21\", \"W17\", \"Mon\", \"\"],\n",
    "            [5, \"整理房間\", \"日常生活\", \"未完成\", \"2026-04-21\", \"W17\", \"Mon\", \"\"],\n",
    "            [6, \"散步 30 分鐘\", \"自我照顧\", \"進行中\", \"2026-04-21\", \"W17\", \"Mon\", \"\"],\n",
    "            [7, \"日文 L36\", \"學習成長\", \"未完成\", \"2026-04-22\", \"W17\", \"Tue\", \"\"],\n",
    "            [8, \"閱讀 30 分鐘\", \"學習成長\", \"進行中\", \"2026-04-22\", \"W17\", \"Tue\", \"\"],\n",
    "            [9, \"晚餐備餐\", \"日常生活\", \"未完成\", \"2026-04-22\", \"W17\", \"Tue\", \"\"],\n",
    "            [10, \"倒垃圾\", \"日常生活\", \"未完成\", \"2026-04-22\", \"W17\", \"Tue\", \"\"],\n",
    "            [11, \"冥想 10 分鐘\", \"自我照顧\", \"已完成\", \"2026-04-22\", \"W17\", \"Tue\", \"\"],\n",
    "            [12, \"日文 L37\", \"學習成長\", \"未完成\", \"2026-04-23\", \"W17\", \"Wed\", \"\"],\n",
    "            [13, \"英單 30 個\", \"學習成長\", \"進行中\", \"2026-04-23\", \"W17\", \"Wed\", \"\"],\n",
    "            [14, \"整理筆記\", \"學習成長\", \"進行中\", \"2026-04-23\", \"W17\", \"Wed\", \"\"],\n",
    "            [15, \"超市採買\", \"日常生活\", \"未完成\", \"2026-04-23\", \"W17\", \"Wed\", \"\"],\n",
    "            [16, \"運動 20 分鐘\", \"自我照顧\", \"未完成\", \"2026-04-23\", \"W17\", \"Wed\", \"\"],\n",
    "            [17, \"日文 L38\", \"學習成長\", \"未完成\", \"2026-04-24\", \"W17\", \"Thu\", \"\"],\n",
    "            [18, \"神經生理複習\", \"學習成長\", \"進行中\", \"2026-04-24\", \"W17\", \"Thu\", \"\"],\n",
    "            [19, \"閱讀 30 分鐘\", \"學習成長\", \"未完成\", \"2026-04-24\", \"W17\", \"Thu\", \"\"],\n",
    "            [20, \"衣物整理\", \"日常生活\", \"未完成\", \"2026-04-24\", \"W17\", \"Thu\", \"\"],\n",
    "            [21, \"伸展 15 分鐘\", \"自我照顧\", \"進行中\", \"2026-04-24\", \"W17\", \"Thu\", \"\"],\n",
    "            [22, \"日文 L39\", \"學習成長\", \"未完成\", \"2026-04-25\", \"W17\", \"Fri\", \"\"],\n",
    "            [23, \"英單 30 個\", \"學習成長\", \"進行中\", \"2026-04-25\", \"W17\", \"Fri\", \"\"],\n",
    "            [24, \"專題報告\", \"學習成長\", \"未完成\", \"2026-04-25\", \"W17\", \"Fri\", \"\"],\n",
    "            [25, \"打掃客廳\", \"日常生活\", \"未完成\", \"2026-04-25\", \"W17\", \"Fri\", \"\"],\n",
    "            [26, \"瑜伽 20 分鐘\", \"自我照顧\", \"進行中\", \"2026-04-25\", \"W17\", \"Fri\", \"\"],\n",
    "            [27, \"複習本週內容\", \"學習成長\", \"進行中\", \"2026-04-26\", \"W17\", \"Sat\", \"\"],\n",
    "            [28, \"整理書櫃\", \"日常生活\", \"未完成\", \"2026-04-26\", \"W17\", \"Sat\", \"\"],\n",
    "            [29, \"採買生活用品\", \"日常生活\", \"未完成\", \"2026-04-26\", \"W17\", \"Sat\", \"\"],\n",
    "            [30, \"追劇 1 集\", \"自我照顧\", \"已完成\", \"2026-04-26\", \"W17\", \"Sat\", \"\"],\n",
    "            [31, \"早睡 11 點\", \"自我照顧\", \"未完成\", \"2026-04-26\", \"W17\", \"Sat\", \"\"],\n",
    "            [32, \"下週計畫\", \"學習成長\", \"進行中\", \"2026-04-27\", \"W17\", \"Sun\", \"\"],\n",
    "            [33, \"日文複習總整理\", \"學習成長\", \"未完成\", \"2026-04-27\", \"W17\", \"Sun\", \"\"],\n",
    "            [34, \"洗床單\", \"日常生活\", \"未完成\", \"2026-04-27\", \"W17\", \"Sun\", \"\"],\n",
    "            [35, \"散步 30 分鐘\", \"自我照顧\", \"進行中\", \"2026-04-27\", \"W17\", \"Sun\", \"\"],\n",
    "            [36, \"早睡 11 點\", \"自我照顧\", \"未完成\", \"2026-04-27\", \"W17\", \"Sun\", \"\"],\n",
    "        ],\n",
    "        columns=[\"id\", \"task_name\", \"category\", \"status\", \"date\", \"week\", \"weekday\", \"note\"],\n",
    "    )\n",
    "    sample.to_csv(path, index=False)\n",
    "\n",
    "\n",
    "@st.cache_data\n",
    "def load_data(path: str = DEFAULT_CSV) -> pd.DataFrame:\n",
    "    if not Path(path).exists():\n",
    "        create_sample_csv(path)\n",
    "    df = pd.read_csv(path)\n",
    "    df[\"date\"] = pd.to_datetime(df[\"date\"]).dt.date\n",
    "    return df\n",
    "\n",
    "\n",
    "def derive_week(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    frame = df.copy()\n",
    "    iso = pd.to_datetime(frame[\"date\"]).dt.isocalendar()\n",
    "    derived = \"W\" + iso.week.astype(str)\n",
    "    frame[\"week\"] = frame[\"week\"].fillna(derived) if \"week\" in frame.columns else derived\n",
    "    return frame\n",
    "\n",
    "\n",
    "def derive_weekday(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    frame = df.copy()\n",
    "    wd = pd.to_datetime(frame[\"date\"]).dt.strftime(\"%a\")\n",
    "    frame[\"weekday\"] = frame[\"weekday\"].fillna(wd) if \"weekday\" in frame.columns else wd\n",
    "    return frame\n",
    "\n",
    "\n",
    "df = derive_weekday(derive_week(load_data()))\n",
    "\n",
    "# =========================\n",
    "# Sidebar: simple uploader\n",
    "# =========================\n",
    "with st.sidebar:\n",
    "    st.markdown(\"### 資料來源\")\n",
    "    uploaded = st.file_uploader(\"上傳 tasks.csv 覆蓋示例資料\", type=[\"csv\"])\n",
    "    if uploaded is not None:\n",
    "        up_df = pd.read_csv(uploaded)\n",
    "        up_df.to_csv(DEFAULT_CSV, index=False)\n",
    "        st.cache_data.clear()\n",
    "        st.success(\"已更新資料，重新整理頁面即可。\")\n",
    "    st.markdown(\"---\")\n",
    "    st.markdown(\"**CSV 必備欄位**\")\n",
    "    st.code(\"id,task_name,category,status,date,week,weekday,note\", language=\"text\")\n",
    "\n",
    "# =========================\n",
    "# Helpers\n",
    "# =========================\n",
    "def get_week_options(frame: pd.DataFrame):\n",
    "    weeks = frame[\"week\"].dropna().astype(str).unique().tolist()\n",
    "    return sorted(weeks, key=lambda x: int(x.replace(\"W\", \"\")))\n",
    "\n",
    "\n",
    "def get_week_range(frame: pd.DataFrame, selected_week: str):\n",
    "    subset = frame[frame[\"week\"] == selected_week]\n",
    "    if subset.empty:\n",
    "        today = date.today()\n",
    "        monday = today - timedelta(days=today.weekday())\n",
    "        return monday, monday + timedelta(days=6)\n",
    "    return subset[\"date\"].min(), subset[\"date\"].max()\n",
    "\n",
    "\n",
    "def badge(status: str) -> str:\n",
    "    bg = STATUS_BG.get(status, \"#EFEFEF\")\n",
    "    color = STATUS_TEXT.get(status, \"#666666\")\n",
    "    return f'<span class=\"badge\" style=\"background:{bg}; color:{color};\">{status}</span>'\n",
    "\n",
    "\n",
    "def render_calendar_html(year: int, month: int, today_value: date, selected_week: str, monday: date, sunday: date):\n",
    "    cal = calendar.Calendar(firstweekday=0)\n",
    "    cells = []\n",
    "    for wd in WEEKDAY_ORDER:\n",
    "        cells.append(f'<div class=\"weekday-label\">{wd}</div>')\n",
    "    for d in cal.itermonthdates(year, month):\n",
    "        cls = \"day-num\"\n",
    "        if d.month != month:\n",
    "            cls += \" day-other\"\n",
    "        if d == today_value:\n",
    "            cls += \" day-today\"\n",
    "        cells.append(f'<div class=\"{cls}\">{d.day}</div>')\n",
    "    return f\"\"\"\n",
    "    <div class=\"shell-card\">\n",
    "        <div class=\"card-title calendar-title\">📅 月曆</div>\n",
    "        <div class=\"card-body\">\n",
    "            <div style=\"text-align:center; font-size:1.45rem; font-weight:700; margin-bottom:10px;\">{year} 年 {month} 月</div>\n",
    "            <div class=\"calendar-grid\">{''.join(cells)}</div>\n",
    "            <div style=\"margin-top:14px; background:{CREAM}; border-radius:12px; padding:10px 12px; color:#6D6466; font-size:0.92rem;\">\n",
    "                ⭐ {selected_week}: {monday.month}/{monday.day} ({monday.strftime('%a')}) ~ {sunday.month}/{sunday.day} ({sunday.strftime('%a')})\n",
    "            </div>\n",
    "        </div>\n",
    "    </div>\n",
    "    \"\"\"\n",
    "\n",
    "\n",
    "def render_today_card(frame: pd.DataFrame, today_value: date):\n",
    "    subset = frame[frame[\"date\"] == today_value]\n",
    "    categories = [\"學習成長\", \"日常生活\", \"自我照顧\"]\n",
    "    blocks = []\n",
    "    for cat in categories:\n",
    "        cat_df = subset[subset[\"category\"] == cat].head(5)\n",
    "        if cat_df.empty:\n",
    "            content = '<div class=\"small-note\">今天這一類目前沒有任務。</div>'\n",
    "        else:\n",
    "            content = \"\".join(\n",
    "                f'<div class=\"mini-row\"><span>☐ {row.task_name}</span>{badge(row.status)}</div>'\n",
    "                for row in cat_df.itertuples()\n",
    "            )\n",
    "        blocks.append(\n",
    "            f'''\n",
    "            <div style=\"background:rgba(255,255,255,0.45); border:1px solid #D7E0EF; border-radius:14px; padding:12px;\">\n",
    "                <div style=\"text-align:center; font-weight:700; margin-bottom:10px;\">{cat}</div>\n",
    "                {content}\n",
    "            </div>\n",
    "            '''\n",
    "        )\n",
    "    return f\"\"\"\n",
    "    <div class=\"shell-card\">\n",
    "        <div class=\"card-title today-title\">📝 今日任務 ({today_value.month}/{today_value.day} {today_value.strftime('%a')})</div>\n",
    "        <div class=\"card-body\">\n",
    "            <div style=\"display:grid; grid-template-columns:repeat(3, 1fr); gap:12px;\">{''.join(blocks)}</div>\n",
    "        </div>\n",
    "    </div>\n",
    "    \"\"\"\n",
    "\n",
    "\n",
    "def render_summary_card(frame: pd.DataFrame, selected_week: str):\n",
    "    subset = frame[frame[\"week\"] == selected_week]\n",
    "    total = len(subset)\n",
    "    done = int((subset[\"status\"] == \"已完成\").sum())\n",
    "    doing = int((subset[\"status\"] == \"進行中\").sum())\n",
    "    todo = int((subset[\"status\"] == \"未完成\").sum())\n",
    "\n",
    "    cat_counts = {\n",
    "        \"學習成長\": int((subset[\"category\"] == \"學習成長\").sum()),\n",
    "        \"日常生活\": int((subset[\"category\"] == \"日常生活\").sum()),\n",
    "        \"自我照顧\": int((subset[\"category\"] == \"自我照顧\").sum()),\n",
    "    }\n",
    "    max_count = max(cat_counts.values()) if cat_counts else 1\n",
    "    rows = []\n",
    "    for label, value in cat_counts.items():\n",
    "        width = 0 if max_count == 0 else int(value / max_count * 100)\n",
    "        rows.append(\n",
    "            f'''\n",
    "            <div class=\"progress-row\">\n",
    "                <div>{label}</div>\n",
    "                <div class=\"bar-bg\"><div class=\"bar-fill\" style=\"width:{width}%; background:{CATEGORY_BAR[label]};\"></div></div>\n",
    "                <div style=\"text-align:right;\">{value}</div>\n",
    "            </div>\n",
    "            '''\n",
    "        )\n",
    "    return f\"\"\"\n",
    "    <div class=\"shell-card\">\n",
    "        <div class=\"card-title summary-title\">📊 本週任務摘要 ({selected_week})</div>\n",
    "        <div class=\"card-body\">\n",
    "            <div class=\"stats-grid\">\n",
    "                <div class=\"stats-box\"><div class=\"stats-label\">總任務</div><div class=\"stats-num\">{total}</div></div>\n",
    "                <div class=\"stats-box\"><div class=\"stats-label\" style=\"color:#5E8A57;\">已完成</div><div class=\"stats-num\" style=\"color:#5E8A57;\">{done}</div></div>\n",
    "                <div class=\"stats-box\"><div class=\"stats-label\" style=\"color:#A87B16;\">進行中</div><div class=\"stats-num\" style=\"color:#A87B16;\">{doing}</div></div>\n",
    "                <div class=\"stats-box\"><div class=\"stats-label\" style=\"color:#BE7484;\">未完成</div><div class=\"stats-num\" style=\"color:#BE7484;\">{todo}</div></div>\n",
    "            </div>\n",
    "            <div style=\"font-weight:700; color:#685A87; margin: 6px 0 8px 0;\">依分類統計</div>\n",
    "            {''.join(rows)}\n",
    "            <div style=\"margin-top:14px; padding:12px; border-radius:12px; background:#F8F5FF;\">🌙 本週目標：保持節奏，穩定前進</div>\n",
    "        </div>\n",
    "    </div>\n",
    "    \"\"\"\n",
    "\n",
    "\n",
    "def render_day_card(day_name: str, day_date: date | None, frame: pd.DataFrame, selected_week: str):\n",
    "    subset = frame[(frame[\"week\"] == selected_week) & (frame[\"weekday\"] == day_name)]\n",
    "    date_str = f\"{day_date.month}/{day_date.day}\" if day_date else \"--/--\"\n",
    "    if subset.empty:\n",
    "        rows = '<div class=\"small-note\">這一天目前沒有任務，可以留白或新增安排。</div>'\n",
    "    else:\n",
    "        rows = \"\".join(\n",
    "            f'''\n",
    "            <div class=\"task-row\">\n",
    "                <div class=\"task-name\"><span class=\"checkbox\"></span><span>{row.task_name}</span></div>\n",
    "                <div>{badge(row.status)}</div>\n",
    "            </div>\n",
    "            '''\n",
    "            for row in subset.itertuples()\n",
    "        )\n",
    "    return f\"\"\"\n",
    "    <div class=\"day-card\">\n",
    "        <div class=\"day-header\">\n",
    "            <div class=\"day-header-title\">{day_name}.</div>\n",
    "            <div class=\"day-header-date\">{date_str}</div>\n",
    "        </div>\n",
    "        <div class=\"day-head-row\"><div>任務項目</div><div>狀態</div></div>\n",
    "        <div class=\"day-list\">{rows}</div>\n",
    "    </div>\n",
    "    \"\"\"\n",
    "\n",
    "\n",
    "# =========================\n",
    "# State\n",
    "# =========================\n",
    "week_options = get_week_options(df)\n",
    "if not week_options:\n",
    "    st.stop()\n",
    "\n",
    "# default choose current week if exists\n",
    "current_week = \"W\" + str(datetime.today().isocalendar().week)\n",
    "default_index = week_options.index(current_week) if current_week in week_options else 0\n",
    "\n",
    "if \"selected_week\" not in st.session_state:\n",
    "    st.session_state.selected_week = week_options[default_index]\n",
    "\n",
    "selected_week = st.session_state.selected_week\n",
    "monday, sunday = get_week_range(df, selected_week)\n",
    "focus_day = monday\n",
    "focus_year = monday.year\n",
    "focus_month = monday.month\n",
    "\n",
    "# =========================\n",
    "# Top banner\n",
    "# =========================\n",
    "st.markdown(\n",
    "    f'''\n",
    "    <div class=\"top-wrap\">\n",
    "        <div>\n",
    "            <div class=\"top-title\">Weekly Planning Dashboard ✧</div>\n",
    "            <div class=\"top-sub\">小小的進步，累積成更好的自己。</div>\n",
    "        </div>\n",
    "        <div class=\"top-sub\">{focus_year} / {calendar.month_abbr[focus_month]} &nbsp;&nbsp;|&nbsp;&nbsp; {selected_week} &nbsp;&nbsp;|&nbsp;&nbsp; Today: {date.today().strftime('%b %d (%a)')}</div>\n",
    "    </div>\n",
    "    ''',\n",
    "    unsafe_allow_html=True,\n",
    ")\n",
    "\n",
    "# =========================\n",
    "# Layout\n",
    "# =========================\n",
    "left_col, right_col = st.columns([1.05, 2.55], gap=\"large\")\n",
    "\n",
    "with left_col:\n",
    "    st.markdown(render_calendar_html(focus_year, focus_month, date.today(), selected_week, monday, sunday), unsafe_allow_html=True)\n",
    "    st.markdown(\"<div style='height:12px;'></div>\", unsafe_allow_html=True)\n",
    "    st.markdown(render_today_card(df, date.today()), unsafe_allow_html=True)\n",
    "    st.markdown(\"<div style='height:12px;'></div>\", unsafe_allow_html=True)\n",
    "    st.markdown(render_summary_card(df, selected_week), unsafe_allow_html=True)\n",
    "\n",
    "with right_col:\n",
    "    c1, c2, c3 = st.columns([1.2, 1.1, 1.4])\n",
    "    with c1:\n",
    "        st.markdown('<div class=\"small-note\" style=\"margin-top:8px;\">本週目標：持續進步，累積成更好的自己。</div>', unsafe_allow_html=True)\n",
    "    with c2:\n",
    "        st.markdown('<div style=\"margin-bottom:4px; font-weight:700; color:#6C6064; text-align:center;\">週次選擇</div>', unsafe_allow_html=True)\n",
    "        chosen = st.selectbox(\"週次\", week_options, index=week_options.index(selected_week), label_visibility=\"collapsed\")\n",
    "        st.session_state.selected_week = chosen\n",
    "        selected_week = chosen\n",
    "        monday, sunday = get_week_range(df, selected_week)\n",
    "    with c3:\n",
    "        st.markdown(\n",
    "            f'<div style=\"text-align:right; margin-top:10px;\"><div style=\"font-size:1.1rem; font-weight:700; color:#413739;\">{monday.year} / {calendar.month_abbr[monday.month]} / 第 {selected_week.replace(\"W\", \"\")} 週</div><div class=\"small-note\">{monday.month}/{monday.day} ({monday.strftime(\"%a\")}) - {sunday.month}/{sunday.day} ({sunday.strftime(\"%a\")})</div></div>',\n",
    "            unsafe_allow_html=True,\n",
    "        )\n",
    "\n",
    "    st.markdown('<div style=\"height:10px\"></div>', unsafe_allow_html=True)\n",
    "\n",
    "    week_dates = [monday + timedelta(days=i) for i in range(7)]\n",
    "\n",
    "    top_days = st.columns(4, gap=\"medium\")\n",
    "    for idx, day_name in enumerate([\"Mon\", \"Tue\", \"Wed\", \"Thu\"]):\n",
    "        with top_days[idx]:\n",
    "            st.markdown(render_day_card(day_name, week_dates[idx], df, selected_week), unsafe_allow_html=True)\n",
    "\n",
    "    st.markdown('<div style=\"height:14px\"></div>', unsafe_allow_html=True)\n",
    "    bottom_left, bottom_mid, bottom_right, memo_col = st.columns([1, 1, 1, 0.82], gap=\"medium\")\n",
    "    with bottom_left:\n",
    "        st.markdown(render_day_card(\"Fri\", week_dates[4], df, selected_week), unsafe_allow_html=True)\n",
    "    with bottom_mid:\n",
    "        st.markdown(render_day_card(\"Sat\", week_dates[5], df, selected_week), unsafe_allow_html=True)\n",
    "    with bottom_right:\n",
    "        st.markdown(render_day_card(\"Sun\", week_dates[6], df, selected_week), unsafe_allow_html=True)\n",
    "    with memo_col:\n",
    "        st.markdown(\n",
    "            '''\n",
    "            <div class=\"memo-box\">\n",
    "                <div class=\"memo-title\">本週備註 ♡</div>\n",
    "                <div class=\"small-note\">\n",
    "                    專注在重要的事，<br>\n",
    "                    不追求完美，<br>\n",
    "                    但求每天有進步。<br><br>\n",
    "                    可以把這裡留給：<br>\n",
    "                    • 本週提醒<br>\n",
    "                    • 小小反思<br>\n",
    "                    • 想記住的一句話\n",
    "                </div>\n",
    "            </div>\n",
    "            ''',\n",
    "            unsafe_allow_html=True,\n",
    "        )\n",
    "\n",
    "st.markdown(\n",
    "    '''\n",
    "    <div class=\"footer-strip\">\n",
    "        <div>快速切換：任務總表　｜　月統計　｜　年計畫　｜　設定</div>\n",
    "        <div>週次切換後，右側與統計會同步更新</div>\n",
    "    </div>\n",
    "    ''',\n",
    "    unsafe_allow_html=True,\n",
    ")\n",
    "\n",
    "with st.expander(\"查看目前使用的資料表\"):\n",
    "    st.dataframe(df, use_container_width=True)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
